### ISSUE TITLE
Include fix to usb-serial-jtag spurious resets

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-flasher-stub#15]
We need to make sure we have something similar to https://github.com/espressif/esptool/commit/32e80148493a83d34bad635287cb97e458d2af58 included in our Rust stubs here.

**Comment by igrr** [comment]
Also to include:

- https://github.com/espressif/esptool/commit/6fd91afec42f7717f02bb41a4bb2789c73187c63
- https://github.com/espressif/esptool/commit/80dc2104e163acddf6a6a6fa26c1e3f7068173c3
