### ISSUE TITLE
Initial release usable in other projects (e.g. esptool-js)

### ISSUE THREAD

**Issue by igrr** [esp-rs/esp-flasher-stub#17]
- [x] Update to latest esp-hal
- [x] Generate releases of stubs, provide [json files](https://github.com/espressif/esptool/tree/master/esptool/targets/stub_flasher) as artifacts
- [x] https://github.com/esp-rs/esp-flasher-stub/issues/12 — Spend at least a few hours looking for opportunities to size reduce the binary size
- [x] https://github.com/esp-rs/esp-flasher-stub/issues/15 — Is a nice-to-have, if we are including the stubs for C3 and S3 into this initial release.

**Comment by jessebraham** [comment]
JSON stub generator and release workflow added in #18

**Comment by dobairoland** [comment]
FYI @DNedic

**Comment by jessebraham** [comment]
I believe all tasks have been completed here, so other than the release itself this issue should be complete?

**Comment by igrr** [comment]
@jessebraham Agree, we can close this and make a release.

**Comment by SergioGasquez** [comment]
Just created https://github.com/esp-rs/espflash/pull/518 to use the generated stubs in `espflash`
