### ISSUE TITLE
Use XTAL_CLOCK as UART source

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/esp-flasher-stub#55]
Stubs rely on this to detect the crystal frequency. 

Blocked until https://github.com/esp-rs/esp-hal/pull/1416 is merged.

**Comment by dobairoland** [comment]
https://github.com/esp-rs/esp-flasher-stub/pull/57 did not address this?

**Comment by SergioGasquez** [comment]
> #57 did not address this?

Yes, forgot to link the PR to this issue.
